spring:
  application:
    name: pokedex
  messages:
    basename: messages,errors
  profiles:
    active: memory

server:
  servlet:
    session:
      tracking-modes:
        - cookie
  error:
    include-message: always
